### PR TITLE
Ci devel

### PR DESCRIPTION
**Pull request by anthonymonori**
Rewrote the travis CI script to reflect their latest development and integration with Android build. Tests needs to be rewritten to be executed, from regular unit tests to the Android testing framework.

### CODE REVIEW

**Comment by christoffer** [comment]
Thanks for doing this! Oh boy, there's been a lot of things happening in Android since I visited last.

I'm a little uncomfortable checking in just the changed setup without any running tests to validate the setup. Would you mind commenting out the actual tests instead of commenting out `assembleTest`, and leave just a single minimal test to verify that the setup is running correctly? I'm thinking something like "assert true" but that uses something that requires the emulator to run.

That would leave the code in an excellent place to continue working on converting the (few) existing tests.

**Comment by anthonymonori** [comment]
Sure thing! I'll add some tests in next week after I am back home; currently traveling.

**Comment by anthonymonori** [comment]
It's been a while, but I'm getting there. Still having migrating all unit tests to run with the new setup, but 26 of the tests do complete successfully, but the import, export and migration fails - something to do with the context and need to do some updating in the test code as well.

If you look at the output of the Travis CI log, more specifically line 1626, you will see the output of the unit tests, and that after it goes ahead and do a "normal build", which succeeds.

After finishing converting all the unit tests, I will start to add instrumentation/UI tests as well.

**Comment by christoffer** [comment]
Hey Anthony!

Thanks for working on this, I really appreciate it. I have some time over this weekend, do you mind if I merge this in, as is, and then spend some time trying to fix the last couple of tests?

**Comment by anthonymonori** [comment]
Would really love that! Got lost in the migtation tests last weekend...
Been neglegting this because of the tests, so would be nice if you could help me through it :) 
Sent from Outlook




On Fri, Nov 13, 2015 at 7:18 PM -0800, "Christoffer Klang" <notifications@github.com> wrote:












Hey Anthony!



Thanks for working on this, I really appreciate it. I have some time over this weekend, do you mind if I merge this in, as is, and then spend some time trying to fix the last couple of tests?

**Comment by christoffer** [comment]
Merged in manually with: d9da15e94e322851015c02d89861f62302ebd3a1

**Pull request closed without merging**
